package classname

const (
	String                        = "java/lang/String"
	Class                         = "java/lang/Class"
	Object                        = "java/lang/Object"
	System                        = "java/lang/System"
	Float                         = "java/lang/Float"
	Double                        = "java/lang/Double"
	Cloneable                     = "java/lang/Cloneable"
	Serializable                  = "java/io/Serializable"
	Throwable                     = "java/lang/Throwable"
	Thread                        = "java/lang/Thread"
	ThreadGroup                   = "java/lang/ThreadGroup"
	VM                            = "sun/misc/VM"
	Unsafe                        = "sun/misc/Unsafe"
	Reflection                    = "sun/reflect/Reflection"
	NativeConstructorAccessorImpl = "sun/reflect/NativeConstructorAccessorImpl"
	FileOutputStream              = "java/io/FileOutputStream"
	FileInputStream               = "java/io/FileInputStream"
	FileDescriptor                = "java/io/FileDescriptor"
	AccessController              = "java/security/AccessController"
	Field                         = "java/lang/reflect/Field"
	Constructor                   = "java/lang/reflect/Constructor"
	AtomicLong                    = "java/util/concurrent/atomic/AtomicLong"
	UnixFileSystem                = "java/io/UnixFileSystem"
	ClassLoader                   = "java/lang/ClassLoader"
	Signal                        = "sun/misc/Signal"
	Runtime                       = "java/lang/Runtime"
	URLClassPath                  = "sun/misc/URLClassPath"
)
